version: '3.8'

services:
  db: # Este es el nombre del servicio
    image: postgres:15-alpine
    container_name: tienda-db
    environment:
      POSTGRES_USER: jmc
      POSTGRES_PASSWORD: YOsd5995$$
      POSTGRES_DB: TiendaTemplate
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: